# BadValueError when updating ndb entity
tuple
