# pdb doesn't respond after pdb.set_trace() call
sys.stdout
