# Django AUTHENTICATION_BACKENDS import error
AUTHENTICATION_BACKENDS = ('apps.apployment_site.auth.CustomAuth',)
