# Python while loop not exiting correctly, 'Out of range' error seen on last iteration
except IndexError:
    pass
continue
