# Django NameError during ManyToMany field referencing
category = models.ManyToManyField('PlayCat')
