# Python functions return 1 when there is an exception
raise
