# Connection Error with DynamoDB2 but not DynamoDB using boto
table2 = Table(tablename, connection=conn2)
