# Django: Integrity error when deleting an object with a 'through' many-to-many field
on_delete
