# django 1.7 relation "auth_user" does not exist in migrate but fine in tests
select * from django_migrations where app='auth'
