# Anaconda3 libhdf5.so.9: cannot open shared object file [works fine on py2.7 but not on py3.4]
conda update --all
