# Crash in PyObject_Call
self
