# Calling goodness of fit value with result.prsquared() in statsmodels results TypeError: 'numpy.float64' object is not callable
print(result.prsquared)
