# python TypeError: 'list' object is not callable error
reachable = graph[node]
