# Python Pymongo auth failed
connection.api.authenticate("root","1234")
