# Django urls.py gives a 404 error while trying to access a URL
url(r'^$', some_view, name='some_view_name'),
